services:
  elevator:
    build: ./
    ports:
      - 8080:8080
    networks:
      - my-network

  client-app:
    build: ./client
    depends_on:
      - elevator
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
